"""save date added

Revision ID: 1615725d56ce
Revises: 290048a72164
Create Date: 2025-08-07 23:49:48.703603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1615725d56ce'
down_revision = '290048a72164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_save_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_save_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
