"""Lab.description and Save.comment fields added

Revision ID: 246eee59b734
Revises: 7f90fbb84cb3
Create Date: 2025-07-30 20:42:40.413596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246eee59b734'
down_revision = '7f90fbb84cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_lab_description'), ['description'])

    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=256), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_save_comment'), ['comment'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_save_comment'), type_='unique')
        batch_op.drop_column('comment')

    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_lab_description'), type_='unique')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
