"""Host os type

Revision ID: 290048a72164
Revises: cf433b44bddb
Create Date: 2025-08-07 01:23:55.703696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290048a72164'
down_revision = 'cf433b44bddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_column('os_type')

    # ### end Alembic commands ###
