"""Save.is_default

Revision ID: 47a6f2b92351
Revises: 7a8852df5bf8
Create Date: 2025-07-30 22:40:33.297663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a6f2b92351'
down_revision = '7a8852df5bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
