"""Backup.uid replaced uuid

Revision ID: 556eaada1d60
Revises: 6ac4bb69fc24
Create Date: 2025-07-30 21:41:42.362855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556eaada1d60'
down_revision = '6ac4bb69fc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.String(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_backup_uuid'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_backup_uid'), ['uid'])
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_backup_uid'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_backup_uuid'), ['uuid'])
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
