"""some unique constraints dropped

Revision ID: 7a8852df5bf8
Revises: 556eaada1d60
Create Date: 2025-07-30 21:46:43.748925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8852df5bf8'
down_revision = '556eaada1d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_backup_comment'), type_='unique')

    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_lab_description'), type_='unique')

    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_save_comment'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_save_comment'), ['comment'])

    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_lab_description'), ['description'])

    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_backup_comment'), ['comment'])

    # ### end Alembic commands ###
