"""Save-Backup one-to-many relation added

Revision ID: 7f90fbb84cb3
Revises: f69438ab99ba
Create Date: 2025-07-30 20:26:14.644866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f90fbb84cb3'
down_revision = 'f69438ab99ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_backup_save_id_save'), 'save', ['save_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_backup_save_id_save'), type_='foreignkey')
        batch_op.drop_column('save_id')

    # ### end Alembic commands ###
