"""hidden lab

Revision ID: 925dc86dda28
Revises: a2f16ff2ad2e
Create Date: 2025-07-31 02:29:09.517461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925dc86dda28'
down_revision = 'a2f16ff2ad2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
