"""Save uid

Revision ID: a2f16ff2ad2e
Revises: b48886663b8d
Create Date: 2025-07-31 00:29:15.369324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f16ff2ad2e'
down_revision = 'b48886663b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_save_uid'), ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_save_uid'), type_='unique')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
