"""remove save is_default nullable

Revision ID: cf433b44bddb
Revises: 925dc86dda28
Create Date: 2025-08-07 00:42:39.490696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf433b44bddb'
down_revision = '925dc86dda28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
