"""dir field added to Backup

Revision ID: d3924914c9e8
Revises: 9956fcf77a55
Create Date: 2025-07-29 13:32:17.347636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3924914c9e8'
down_revision = '9956fcf77a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dir', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup', schema=None) as batch_op:
        batch_op.drop_column('dir')

    # ### end Alembic commands ###
