"""GroupBackup model added

Revision ID: f69438ab99ba
Revises: 
Create Date: 2025-07-30 20:00:52.627537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69438ab99ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host')),
    sa.UniqueConstraint('ip', name=op.f('uq_host_ip')),
    sa.UniqueConstraint('name', name=op.f('uq_host_name'))
    )
    op.create_table('lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab')),
    sa.UniqueConstraint('name', name=op.f('uq_lab_name'))
    )
    op.create_table('backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('dir', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], name=op.f('fk_backup_host_id_host')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup')),
    sa.UniqueConstraint('comment', name=op.f('uq_backup_comment')),
    sa.UniqueConstraint('uuid', name=op.f('uq_backup_uuid'))
    )
    op.create_table('save',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], name=op.f('fk_save_lab_id_lab')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_save'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save')
    op.drop_table('backup')
    op.drop_table('lab')
    op.drop_table('host')
    # ### end Alembic commands ###
